### ISSUE TITLE
using local models (Windows)

### ISSUE THREAD

**Issue by ramz35** [dakshesh14/anukool#3]
0. The application can use gguf models!

1. I have local models (gguf) in another directory since they are used by more than one application.  I don't want to have to copy the same instance of the model to each application's preferred directory.  I know in Linux you can use link but in Windows this is more involved as the standard .lnk file won't work.  Even if I put in the full path to the model in .env the application expects to see the models in the .\model directory.  I had to change helper.py to ignore the local model directory and use the full path as set in .env .  I'm sure there is a more optimal way to accommodate this.

2. in Windows I had to use a double \ (\\) in the path because using just a single \ caused the path to be read incorrectly.

**Comment by dakshesh14** [comment]
I have made changes to the code to use the full path to the model. In the `.env` file you can put the full path to the `gguf` model. You can refer to this [PR](https://github.com/dakshesh14/anukool/pull/6) for all the changes.
