### ISSUE TITLE
using HuggingFace embedding requires pip install sentence-transformers

### ISSUE THREAD

**Issue by ramz35** [dakshesh14/anukool#5]
> Traceback (most recent call last):
>   File "C:\Repository\Coding\GenerativeAI\anukool\venv\lib\site-packages\langchain_community\embeddings\huggingface.py", line 59, in __init__
>     import sentence_transformers
> ModuleNotFoundError: No module named 'sentence_transformers'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Repository\Coding\GenerativeAI\anukool\ingest.py", line 105, in <module>
>     create_vector_database()
>   File "C:\Repository\Coding\GenerativeAI\anukool\ingest.py", line 73, in create_vector_database
>     embeddings = HuggingFaceEmbeddings(
>   File "C:\Repository\Coding\GenerativeAI\anukool\venv\lib\site-packages\langchain_community\embeddings\huggingface.py", line 62, in __init__
>     raise ImportError(
> ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.

once I `pip install sentence-transformers`  then it seemed to work.

**Comment by dakshesh14** [comment]
I added `sentence-transformers` to the requirements. Please refer to this [PR](https://github.com/dakshesh14/anukool/pull/6) for more details.
